server:
    contextPath: /SpringToken

spring:
    datasource:
        url: jdbc:hsqldb:mem:testdb
        driverClassName: org.hsqldb.jdbcDriver
        username: sa
        password:
        platform: hsqldb
