server:
    contextPath: /SpringToken

spring:
    datasource:
        url: jdbc:hsqldb:mem:testdb
        driverClassName: org.hsqldb.jdbcDriver
        username: sa
        password:
        platform: hsqldb
    profiles:
        active: staging
    data:
        elasticsearch:
            cluster-nodes: localhost:9300
            repositories:
                enabled: true

# Please note: Active profiles can be set
# Dynamically at build time through resource filtering in Gradle
#By passing it as command line argument during gradle build with -P option