server:
    contextPath: /SpringToken

spring:
    datasource:
        url: jdbc:hsqldb:mem:testdb
        driverClassName: org.hsqldb.jdbcDriver
        username: sa
        password:
        platform: hsqldb
    profiles:
        active: staging

# Please note: Active profiles can be set
# Dynamically at build time through resource filtering in Gradle